### PR TITLE
CODE-OF-CONDUCT.md hyperlink update

### PR DESCRIPTION
**Pull request by osalbahr**
Message "Branch master was renamed to main." when opening the link.

### CODE REVIEW

**Comment by debarshiray** [comment]
```
fedora-rawhide | not ok 1 setup_suite
fedora-rawhide | # (from function `assert_success' in file test/system/libs/bats-assert/src/assert.bash, line 114,
fedora-rawhide | #  from function `_setup_docker_registry' in file test/system/libs/helpers.bash, line 178,
fedora-rawhide | #  from function `setup_suite' in test file test/system/setup_suite.bash, line 58)
fedora-rawhide | #   `_setup_docker_registry' failed
```

**Comment by debarshiray** [comment]
@osalbahr Thanks for noticing this!

Would it be possible for you to use a real email address instead of *...@users.noreply.github.com*?

**Comment by osalbahr** [comment]
> @osalbahr Thanks for noticing this!
> 
> Would it be possible for you to use a real email address instead of _[...@users.noreply.github.com](mailto:...@users.noreply.github.com)_?

You're welcome!

And yes, I can. Should I `git commit --amend` or use some other method to edit the email associated with the commit?

**Comment by debarshiray** [comment]
> > @osalbahr Thanks for noticing this!
> > Would it be possible for you to use a real email address instead of _[...@users.noreply.github.com](mailto:...@users.noreply.github.com)_?
> 
> You're welcome!
> 
> And yes, I can. Should I `git commit --amend` or use some other method to edit the email associated with the commit?

`git commit --amend --author ... -CHEAD` should work.

**Comment by osalbahr** [comment]
> > > @osalbahr Thanks for noticing this!
> > > Would it be possible for you to use a real email address instead of _[...@users.noreply.github.com](mailto:...@users.noreply.github.com)_?
> > 
> > 
> > You're welcome!
> > And yes, I can. Should I `git commit --amend` or use some other method to edit the email associated with the commit?
> 
> `git commit --amend --author ... -CHEAD` should work.

```console
REDACTED:toolbox dracula$ git commit --amend --author "osalbahr@ncsu.edu" -CHEAD
fatal: --author 'osalbahr@ncsu.edu' is not 'Name <email>' and matches no existing author
REDACTED:toolbox dracula$ git commit --amend --author "Osama Albahrani osalbahr@ncsu.edu" -CHEAD
fatal: --author 'Osama Albahrani osalbahr@ncsu.edu' is not 'Name <email>' and matches no existing author
REDACTED:toolbox dracula$ 
```

How do I use it?

**Comment by osalbahr** [comment]
> > > @osalbahr Thanks for noticing this!
> > > Would it be possible for you to use a real email address instead of _[...@users.noreply.github.com](mailto:...@users.noreply.github.com)_?
> > 
> > 
> > You're welcome!
> > And yes, I can. Should I `git commit --amend` or use some other method to edit the email associated with the commit?
> 
> `git commit --amend --author ... -CHEAD` should work.

```console
REDACTED:toolbox dracula$ git commit --amend --author "osalbahr@ncsu.edu" -CHEAD
fatal: --author 'osalbahr@ncsu.edu' is not 'Name <email>' and matches no existing author
REDACTED:toolbox dracula$ git commit --amend --author "Osama Albahrani osalbahr@ncsu.edu" -CHEAD
fatal: --author 'Osama Albahrani osalbahr@ncsu.edu' is not 'Name <email>' and matches no existing author
REDACTED:toolbox dracula$ 
```

How do I use it?

**Comment by osalbahr** [comment]
What should I do after the amend?

```console
REDACTED:toolbox dracula$ git branch
  main
* osalbahr/update-code-of-conduct-hyperlink
REDACTED:toolbox dracula$ git status
On branch osalbahr/update-code-of-conduct-hyperlink
Your branch is up to date with 'origin/osalbahr/update-code-of-conduct-hyperlink'.

nothing to commit, working tree clean
REDACTED:toolbox dracula$ git pull
Already up to date.
REDACTED:toolbox dracula$ git commit --amend --author "Osama Albahrani <osalbahr@ncsu.edu>" -CHEAD
[osalbahr/update-code-of-conduct-hyperlink a06e923] CODE-OF-CONDUCT.md hyperlink update
 Author: Osama Albahrani <osalbahr@ncsu.edu>
 Date: Mon Jun 26 15:01:53 2023 -0400
 1 file changed, 1 insertion(+), 1 deletion(-)
REDACTED:toolbox dracula$ git status
On branch osalbahr/update-code-of-conduct-hyperlink
Your branch and 'origin/osalbahr/update-code-of-conduct-hyperlink' have diverged,
and have 1 and 1 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

nothing to commit, working tree clean
REDACTED:toolbox dracula$ git pull
hint: You have divergent branches and need to specify how to reconcile them.
hint: You can do so by running one of the following commands sometime before
hint: your next pull:
hint: 
hint:   git config pull.rebase false  # merge
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint: 
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
fatal: Need to specify how to reconcile divergent branches.
REDACTED:toolbox dracula$ git push
To ssh://github.com/osalbahr/toolbox.git
 ! [rejected]        osalbahr/update-code-of-conduct-hyperlink -> osalbahr/update-code-of-conduct-hyperlink (non-fast-forward)
error: failed to push some refs to 'ssh://github.com/osalbahr/toolbox.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
REDACTED:toolbox dracula$ 
```

**Comment by debarshiray** [comment]
> What should I do after the amend? Should I merge or rebase?
> 
> ```
> REDACTED:toolbox dracula$ git branch
>   main
> * osalbahr/update-code-of-conduct-hyperlink
> REDACTED:toolbox dracula$ git status
> On branch osalbahr/update-code-of-conduct-hyperlink
> Your branch is up to date with 'origin/osalbahr/update-code-of-conduct-hyperlink'.
> 
> nothing to commit, working tree clean
> REDACTED:toolbox dracula$ git pull
> Already up to date.
> REDACTED:toolbox dracula$ git commit --amend --author "Osama Albahrani <osalbahr@ncsu.edu>" -CHEAD
> [osalbahr/update-code-of-conduct-hyperlink a06e923] CODE-OF-CONDUCT.md hyperlink update
>  Author: Osama Albahrani <osalbahr@ncsu.edu>
>  Date: Mon Jun 26 15:01:53 2023 -0400
>  1 file changed, 1 insertion(+), 1 deletion(-)
> REDACTED:toolbox dracula$ git status
> On branch osalbahr/update-code-of-conduct-hyperlink
> Your branch and 'origin/osalbahr/update-code-of-conduct-hyperlink' have diverged,
> and have 1 and 1 different commits each, respectively.
>   (use "git pull" to merge the remote branch into yours)
> 
> nothing to commit, working tree clean
> REDACTED:toolbox dracula$ git pull
> hint: You have divergent branches and need to specify how to reconcile them.
> hint: You can do so by running one of the following commands sometime before
> hint: your next pull:
> hint: 
> hint:   git config pull.rebase false  # merge
> hint:   git config pull.rebase true   # rebase
> hint:   git config pull.ff only       # fast-forward only
> hint: 
> hint: You can replace "git config" with "git config --global" to set a default
> hint: preference for all repositories. You can also pass --rebase, --no-rebase,
> hint: or --ff-only on the command line to override the configured default per
> hint: invocation.
> fatal: Need to specify how to reconcile divergent branches.
> ...
> ...
> ```

That last `git pull` is where things went wrong.  When I do a `git log` inside your branch, I see:
```
commit ba5d20c633ae857793bd97bc56b2a2c5e6e16ccd (osalbahr/update-code-of-conduct-hyperlink, osalbahr/osalbahr/update-code-of-conduct-hyperlink)
Author: Osama Albahrani <54853250+osalbahr@users.noreply.github.com>
Date:   Mon Jun 26 15:01:53 2023 -0400

    CODE-OF-CONDUCT.md hyperlink update
    
    Message "Branch master was renamed to main." when opening the link.
```

While a lot of places suggest doing `git pull` and `git push` as the *easy* way to work with Git, I have found them to be too problematic with any non-trivial project.  I split the `git pull` into `git fetch` and `git rebase`, and explicitly spell out the arguments to `git push`.  eg., In this case, I would do:
```
$ git checkout main
$ git fetch --prune origin
$ git rebase origin/main
$ git checkout osalbahr/update-code-of-conduct-hyperlink
$ git commit --amend --author "Osama Albahrani <osalbahr@ncsu.edu>" -CHEAD
$ git rebase main
$ git push --force osalbahr osalbahr/update-code-of-conduct-hyperlink:osalbahr/update-code-of-conduct-hyperlink
```

**Review by debarshiray — COMMENTED** [review]
Thanks for  the update!  Even though there was some confusion with Git, it's clear what you meant from your comments.  So, I took the liberty to fix it up and update the branch.

**Comment by debarshiray** [comment]
> Thx for the explanation! I actually just did `git push --force`.

I noticed, but I don't think it fixed the problem.  You can always check before pushing with `git log`.

So, I re-pushed my fixed copy so that we can merge this pull request.  :)

Let's wait for the CI to finish and then I will merge it.

**Comment by osalbahr** [comment]
> > Thx for the explanation! I actually just did `git push --force`.
> 
> I noticed, but I don't think it fixed the problem. You can always check before pushing with `git log`.
> 
> So, I re-pushed my fixed copy so that we can merge this pull request. :)
> 
> Let's wait for the CI to finish and then I will merge it.

Oh, interesting. I'll use `git log` (or `git blame`) next time to check that the commit information was correct before pussing. Not sure why `git commit --amend --author "osalbahr@ncsu.edu" -CHEAD` and then `git push --force` didn't do it.

**Comment by debarshiray** [comment]
> I'll use `git log` (or `git blame`) next time to check that the commit information was correct before pussing. Not sure why `git commit --amend --author "osalbahr@ncsu.edu" -CHEAD` and then `git push --force` didn't do it.

See my comment above.  The problem occurred at that `git pull` step.

Anyway, thanks for your contribution!

**Comment by osalbahr** [comment]
> > I'll use `git log` (or `git blame`) next time to check that the commit information was correct before pussing. Not sure why `git commit --amend --author "osalbahr@ncsu.edu" -CHEAD` and then `git push --force` didn't do it.
> 
> See my comment above. The problem occurred at that `git pull` step.
> 
> Anyway, thanks for your contribution!

Oh. How did `git pull` cause a problem? I thought I should always pull before pushing.

**Pull request merged**
