### PR TITLE
images: Create F37 toolbox image from F36

### PR DESCRIPTION
**Pull request by travier**
Related to https://github.com/containers/toolbox/issues/1011

### CODE REVIEW

**Comment by juhp** [comment]
Thank you! 
But note the actual container definition lives in
https://src.fedoraproject.org/container/fedora-toolbox/tree/rawhide
for now - the files are just a reference copy of that basically.

**Comment by HarryMichal** [comment]
> Thank you! 
> But note the actual fedora-toolbox container definition lives in
> https://src.fedoraproject.org/container/fedora-toolbox/tree/rawhide

I'll add that piece of info into the directory. Without it is confusing.

**Comment by travier** [comment]
Hum, OK. I'll update that with the content from the Fedora repo then.

**Comment by HarryMichal** [comment]
Thank you, @travier!

**Pull request merged**
