### PR TITLE
Prepare 0.1.0

### PR DESCRIPTION
**Pull request by debarshiray**

### CODE REVIEW

**Comment by debarshiray** [comment]
Looks like a network or `registry.access.redhat.com` problem:
```
TASK [Run the commands-options system tests]
fedora-rawhide | 1..234
fedora-rawhide | # test suite: Set up
fedora-rawhide | # test suite: Tear down
fedora-rawhide | not ok 1 setup_suite
fedora-rawhide | # (from function `setup_suite' in test file test/system/setup_suite.bash, line 53)
fedora-rawhide | #   `_pull_and_cache_distro_image rhel 8.10 || false' failed
fedora-rawhide | # Failed to cache image registry.access.redhat.com/ubi8/toolbox:8.10 to /var/tmp/bats-run-8NAmNg/suite/image-cache/rhel-toolbox-8.10
fedora-rawhide | # time="2024-10-22T20:13:13Z" level=fatal msg="initializing source docker://registry.access.redhat.com/ubi8/toolbox:8.10: pinging container registry registry.access.redhat.com: Get \"https://registry.access.redhat.com/v2/\": dial tcp: lookup registry.access.redhat.com: no such host"
fedora-rawhide | # bats warning: Executed 1 instead of expected 234 tests
```

**Comment by debarshiray** [comment]
recheck

**Comment by debarshiray** [comment]
recheck

**Comment by debarshiray** [comment]
> Looks like a network or `registry.access.redhat.com` problem:
> 
> ```
> TASK [Run the commands-options system tests]
> fedora-rawhide | 1..234
> fedora-rawhide | # test suite: Set up
> fedora-rawhide | # test suite: Tear down
> fedora-rawhide | not ok 1 setup_suite
> fedora-rawhide | # (from function `setup_suite' in test file test/system/setup_suite.bash, line 53)
> fedora-rawhide | #   `_pull_and_cache_distro_image rhel 8.10 || false' failed
> fedora-rawhide | # Failed to cache image registry.access.redhat.com/ubi8/toolbox:8.10 to /var/tmp/bats-run-8NAmNg/suite/image-cache/rhel-toolbox-8.10
> fedora-rawhide | # time="2024-10-22T20:13:13Z" level=fatal msg="initializing source docker://registry.access.redhat.com/ubi8/toolbox:8.10: pinging container registry registry.access.redhat.com: Get \"https://registry.access.redhat.com/v2/\": dial tcp: lookup registry.access.redhat.com: no such host"
> fedora-rawhide | # bats warning: Executed 1 instead of expected 234 tests
> ```

@TristanCacqueray @danpawlik Hey!  Any idea what's wrong with the network?  It looks like Software Factory can't reach `registry.access.redhat.com`.

I can reach `registry.access.redhat.com` from my local machine and so can the GitHub Actions workflow.

**Comment by debarshiray** [comment]
recheck

**Comment by TristanCacqueray** [comment]
Looks like an issue with the cloud provider dns, from a test instance:

```ShellSession
[zuul-worker@np0004961386 ~]$ cat /etc/resolv.conf
# This is /run/systemd/resolve/stub-resolv.conf managed by man:systemd-resolved(8).
# Do not edit.

nameserver 127.0.0.53
options edns0 trust-ad
search .

[zuul-worker@np0004961386 ~]$ curl https://registry.access.redhat.com/v2/
curl: (6) Could not resolve host: registry.access.redhat.com
```

**Comment by debarshiray** [comment]
> Looks like an issue with the cloud provider dns, from a test instance:

Thanks for checking.  I wonder if it's a matter of waiting for some DNS caches to expire.

**Comment by danpawlik** [comment]
recheck

**Pull request merged**
