### PR TITLE
.github/CODEOWNERS: Clarify ownership of the CI on Ubuntu

### PR DESCRIPTION
**Pull request by debarshiray**
/cc @Jmennius

### CODE REVIEW

**Comment by debarshiray** [comment]
Ping @Jmennius

**Comment by debarshiray** [comment]
Ping @Jmennius

**Review by Jmennius — APPROVED** [review]
Oh, I need to check this out :)
Sorry I missed it, I was thinking it was something we've already done.

**Comment by debarshiray** [comment]
> Oh, I need to check this out :) Sorry I missed it, I was thinking it was something we've already done.

No problem!  Thanks for checking it out.

**Pull request merged**
