### PR TITLE
Build ubuntu-toolbx:ppc64le images

### PR DESCRIPTION
**Pull request by runlevel5**
## Changes

* Add ppc64le into the build matrix

### CODE REVIEW

**Review by Jmennius — APPROVED** [review]

**Comment by juhp** [comment]
My ignorance here, but does this actually do anything? :)

**Comment by runlevel5** [comment]
> does this actually do anything?

Are you implying about this Pull Request OR the Ubuntu PPC64LE in general?

**Comment by juhp** [comment]
Yes, I mean I don't think there are any ppc64le github builders here.

**Comment by runlevel5** [comment]
> Yes, I mean I don't think there are any ppc64le github builders here.

The docker/build-and-push action actually uses Docker buildx that support cross-compilation

**Comment by runlevel5** [comment]
@debarshiray wondering if you could help review this PR? The OpenPOWER community would really appreciate if this PR is accepted

**Comment by debarshiray** [comment]
> @debarshiray wondering if you could help review this PR? The OpenPOWER community would really appreciate if this PR is accepted

Oops, my apologies.  I failed to notice this one sooner.

Since @Jmennius is fine with `ppc64le` support, I am too.  :)

I just rebased this on top of `main`, and now waiting for the CI to finish before merging.

**Review by debarshiray — COMMENTED** [review]
There are some test failures on Fedora Rawhide.  For example:
```
fedora-rawhide | not ok 3 help: Run command 'help' in 145ms
fedora-rawhide | # (from function `assert_line' in file test/system/libs/bats-assert/src/assert.bash, line 479,
fedora-rawhide | #  in test file test/system/002-help.bats, line 45)
fedora-rawhide | #   `assert_line --index 0 --partial "toolbox(1)"' failed
fedora-rawhide | # /usr/bin/man
fedora-rawhide | #
fedora-rawhide | # -- line does not contain substring --
fedora-rawhide | # index     : 0
fedora-rawhide | # substring : toolbox(1)
fedora-rawhide | # line      : troff:<standard input>:33: warning: cannot select font 'C'
fedora-rawhide | # --
```

I believe these are because of changes in various other components in Fedora 39, which we need to track down one by one and work out a fix.

In the mean time, I am going to temporarily override these failures.

**Comment by debarshiray** [comment]
Thanks for working on this, @runlevel5 !

**Comment by runlevel5** [comment]
@debarshiray the main branch's build failed (ref: https://github.com/containers/toolbox/actions/runs/6335684027/job/17207287730) wondering if you could restart the whole build? Many thanks

**Pull request merged**
