### PR TITLE
images: add Debian 10, 11, 12, testing, and unstable

### PR DESCRIPTION
**Pull request by pennbauman**
Builds of the new Debian images can be found [quay.io/repository/pennbauman/debian-toolbox](https://quay.io/repository/pennbauman/debian-toolbox) if needed for testing.

### CODE REVIEW

**Comment by danpawlik** [comment]
recheck

**Comment by pennbauman** [comment]
The tests will not be able to successed unless the debian-toolbox images are already present in [quay.io/toolbx](https://quay.io/organization/toolbx)

**Comment by juhp** [comment]
Btw the current images are already at: https://quay.io/repository/toolbx-images/debian-toolbox?tab=tags

**Comment by pennbauman** [comment]
I've rearranged the commits, so that image building workflows appear before the images are required by tests. The final commit with system tests is still available on the [preview branch](https://github.com/pennbauman/toolbox/tree/preview) of my fork

**Comment by pennbauman** [comment]
I've rebased these patches on the current main branch, and fixed a couple `shellcheck` errors.

**Pull request closed without merging**
