### PR TITLE
First attempt at a CentOS-8 toolbox container.

### PR DESCRIPTION
**Pull request by kronenpj**
Usage once it's available:

```bash
toolbox create --image centos-toolbox:8 tboxname
toolbox enter tboxname
{Do cool toolbox stuff here.}
```

### CODE REVIEW

**Comment by kronenpj** [comment]
Sorry about the extra files/deletions, I started from the wrong branch.

**Comment by HarryMichal** [comment]
Hi @kronenpj, thanks for the PR. You can always squash your commits and then force-push them.

**Comment by kronenpj** [comment]
I didn't realize until it was already a PR, which I suppose I could have closed and re-opened but I didn't.

**Comment by mnuccioarpae** [comment]
Is help needed to get this merged? It's not clear what is missing.

**Comment by kronenpj** [comment]
> Is help needed to get this merged? It's not clear what is missing.

I wonder if I need to specifically request review somehow. @debarshiray what's the process?

**Comment by kronenpj** [comment]
recheck

**Comment by juhp** [comment]
Recently I made a ubi8 toolbox directly from ubi8/ubi (and also ubi7/ubi).
I expect Centos would work just as well.
The only thing I really needed to do as to post-install sudo via su.
Personally I would prefer we try to move away from toolbox images and just use base images.

**Comment by juhp** [comment]
> I expect Centos would work just as well.

Seems not :-(
With centos:8 `su` seems to need a passwd...

**Comment by kronenpj** [comment]
Try using `sudo` instead of `su`. The account passwords are not set within the toolbox.

**Comment by juhp** [comment]
(I was talking about `toolbox create --image registry.centos.org/centos:8 --container centos8`.)

**Comment by kronenpj** [comment]
That doesn't work with toolbox. Toolbox images are created specially for toolbox, based on the generic OS image. Try https://gitlab.com/uppercat/tlbx/ for your use case.

**Comment by juhp** [comment]
I manged to get your [centos:8 toolbox image](https://github.com/kronenpj/toolbox/blob/master/images/centos/8/Dockerfile) working (on a current SB32 vm).

(I just had to comment out the line:
`RUN ln -s /etc/os-release /usr/lib/os-release`.
Perhaps that is already reflected in this PR?)

**Comment by debarshiray** [comment]
Closing.

See https://github.com/containers/toolbox/issues/275

**Pull request closed without merging**
