### PR TITLE
.zuul: Enable testing on Fedora 40

### PR DESCRIPTION
**Pull request by debarshiray**

### CODE REVIEW

**Comment by debarshiray** [comment]
recheck

**Comment by debarshiray** [comment]
recheck

**Comment by debarshiray** [comment]
recheck

**Comment by debarshiray** [comment]
@danpawlik , @TristanCacqueray do you have any idea what's wrong with the `cloud-fedora-40` instances?  It says that it's timing out, but that's not the real problem.  It has the same timeout of 4800 seconds as Fedora Rawhide, which is more than the 3600 seconds that we use for the other stable Fedoras.

It gets stuck setting up the test suite and doesn't ever progress:
```
2024-03-13 15:22:14.061987 | TASK [Run system tests]
2024-03-13 15:22:17.033732 | fedora-40 | 1..340
2024-03-13 15:22:17.089197 | fedora-40 | # test suite: Set up
2024-03-13 16:37:39.488832 | RUN END RESULT_TIMED_OUT: [untrusted : github.com/containers/toolbox/playbooks/system-test.yaml@main]
```

**Comment by danpawlik** [comment]
hi @debarshiray . No idea, I will try to take a look soon/tomorrow.

**Comment by danpawlik** [comment]
recheck

**Comment by danpawlik** [comment]
```
[zuul-worker@np0004540292 toolbox]$  bats --timing ./test/system --verbose-run

 ✗ setup_suite []
   test suite: Tear down
   (from function `assert_success' in file test/system/libs/bats-assert/src/assert.bash, line 114,
    from function `_setup_docker_registry' in file test/system/libs/helpers.bash, line 207,
    from function `setup_suite' in test file test/system/setup_suite.bash, line 59)
     `_setup_docker_registry' failed

   -- command failed --
   status : 125
   output : Error: creating container storage: the container name "docker-registry" is already in use by d2d37be87ae8cce285711d47ec0a7dfb090306241518e6ec767fa011de74a795. You have to remove that container to be able to reuse that name: that name is already in use, or use --replace to instruct Podman to do so.
   --

   docker-registry
   d2d37be87ae8cce285711d47ec0a7dfb090306241518e6ec767fa011de74a795
   Untagged: quay.io/toolbox_tests/registry:latest
   Deleted: fea5a12cde107bb407bc44ede6dd9edea1d2b4171cd8e52b0cb330bf45e517e1
   bats warning: Executed 1 instead of expected 340 tests

340 tests, 1 failure, 339 not run in 50 seconds
```

**Comment by danpawlik** [comment]
by using command:
```
bats --timing ./test/system -x
```

I spotted, that it stuck on:
```
$ run "$PODMAN" --root "${DOCKER_REG_ROOT}" run -d --rm --name "${DOCKER_REG_NAME}" --privileged -v "${DOCKER_REG_AUTH_DIR}":/auth -e REGISTRY_AUTH=htpasswd -e REGISTRY_AUTH_HTPASSWD_REALM="Registry Realm" -e REGISTRY_AUTH_HTPASSWD_PATH="/auth/htpasswd" -v "${DOCKER_REG_CERTS_DIR}":/certs -e REGISTRY_HTTP_ADDR=0.0.0.0:443 -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt -e REGISTRY_HTTP_TLS_KEY=/certs/domain.key -p 50000:443 "${IMAGES[docker-reg]}"
$ assert_success
$ run "$PODMAN" login --authfile "${TEMP_BASE_DIR}/authfile.json" --username user --password user "${DOCKER_REG_URI}"
$ assert_success
$ run "$SKOPEO" copy --dest-authfile "${TEMP_BASE_DIR}/authfile.json" dir:"${IMAGE_CACHE_DIR}"/fedora-toolbox-34 docker://"${DOCKER_REG_URI}"/fedora-toolbox:34  #### HERE ####
```

**Comment by danpawlik** [comment]
@debarshiray did you try with updated images?

**Comment by debarshiray** [comment]
> @debarshiray did you try with updated images?

Sorry, I got pulled away by some other Fedora 40 and internal deadlines.  Let me try now.  Thanks for confirming that there's nothing wrong with Zuul.

**Comment by debarshiray** [comment]
> I spotted, that it stuck on:
> 
> ```
> $ run "$PODMAN" --root "${DOCKER_REG_ROOT}" run -d --rm --name "${DOCKER_REG_NAME}" --privileged -v "${DOCKER_REG_AUTH_DIR}":/auth -e REGISTRY_AUTH=htpasswd -e REGISTRY_AUTH_HTPASSWD_REALM="Registry Realm" -e REGISTRY_AUTH_HTPASSWD_PATH="/auth/htpasswd" -v "${DOCKER_REG_CERTS_DIR}":/certs -e REGISTRY_HTTP_ADDR=0.0.0.0:443 -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt -e REGISTRY_HTTP_TLS_KEY=/certs/domain.key -p 50000:443 "${IMAGES[docker-reg]}"
> $ assert_success
> $ run "$PODMAN" login --authfile "${TEMP_BASE_DIR}/authfile.json" --username user --password user "${DOCKER_REG_URI}"
> $ assert_success
> $ run "$SKOPEO" copy --dest-authfile "${TEMP_BASE_DIR}/authfile.json" dir:"${IMAGE_CACHE_DIR}"/fedora-toolbox-34 docker://"${DOCKER_REG_URI}"/fedora-toolbox:34  #### HERE ####
> ```

I added a debug commit to run the tests with `bats --trace ...`, and it shows me the same thing.

Interestingly, it also gets stuck on Fedora Rawhide now, in addition to F40.

> so it might be not working on F40. Try to bump the base image to f38

It's trying to use `skopeo(1)` to upload a `fedora-toolbox:34` image that was already downloaded into a local directory onto a temporary local Docker registry created by the test suite.  So, I don't think the `fedora-toolbox:34` image disappeared from `registry.fedoraproject.org`, because the image got downloaded.  For some reason the `skopeo copy ...` can't upload it.

I think I will need a Fedora 40 system to debug this.  Fedora 40 Beta will be released later today, so it's good timing.  :)

For context:

We download a bunch of images using `skopeo copy ...` while setting up the test suite, and cache them in a separate directory using the `dir:` notation, where they don't show up in `podman images`, etc..  Then we use `skopeo copy ...` to either place them in `containers-storage:` to make them visible to Podman, or to upload them to the temporary local Docker registry created by the test suite, as necessary.  This way each test can start with a clean slate, but we don't have to repeatedly download the images again and again.

**Comment by danpawlik** [comment]
recheck

**Comment by debarshiray** [comment]
There's this spew coming from the system tests on Fedora Rawhide:
```
TASK [Run system tests]
fedora-rawhide | /home/zuul-worker/src/github.com/containers/toolbox/test/system/libs/helpers.bash: line 7: TEMP_BASE_DIR: readonly variable
fedora-rawhide | /home/zuul-worker/src/github.com/containers/toolbox/test/system/libs/helpers.bash: line 8: TEMP_STORAGE_DIR: readonly variable
fedora-rawhide | /home/zuul-worker/src/github.com/containers/toolbox/test/system/libs/helpers.bash: line 10: IMAGE_CACHE_DIR: readonly variable
fedora-rawhide | /home/zuul-worker/src/github.com/containers/toolbox/test/system/libs/helpers.bash: line 11: ROOTLESS_PODMAN_STORE_DIR: readonly variable
fedora-rawhide | /home/zuul-worker/src/github.com/containers/toolbox/test/system/libs/helpers.bash: line 12: ROOTLESS_PODMAN_RUNROOT_DIR: readonly variable
fedora-rawhide | /home/zuul-worker/src/github.com/containers/toolbox/test/system/libs/helpers.bash: line 13: PODMAN_STORE_CONFIG_FILE: readonly variable
fedora-rawhide | /home/zuul-worker/src/github.com/containers/toolbox/test/system/libs/helpers.bash: line 14: DOCKER_REG_ROOT: readonly variable
fedora-rawhide | /home/zuul-worker/src/github.com/containers/toolbox/test/system/libs/helpers.bash: line 15: DOCKER_REG_CERTS_DIR: readonly variable
fedora-rawhide | /home/zuul-worker/src/github.com/containers/toolbox/test/system/libs/helpers.bash: line 16: DOCKER_REG_AUTH_DIR: readonly variable
fedora-rawhide | /home/zuul-worker/src/github.com/containers/toolbox/test/system/libs/helpers.bash: line 17: DOCKER_REG_URI: readonly variable
fedora-rawhide | /home/zuul-worker/src/github.com/containers/toolbox/test/system/libs/helpers.bash: line 18: DOCKER_REG_NAME: readonly variable
fedora-rawhide | /home/zuul-worker/src/github.com/containers/toolbox/test/system/libs/helpers.bash: line 21: PODMAN: readonly variable
fedora-rawhide | /home/zuul-worker/src/github.com/containers/toolbox/test/system/libs/helpers.bash: line 22: TOOLBX: readonly variable
fedora-rawhide | /home/zuul-worker/src/github.com/containers/toolbox/test/system/libs/helpers.bash: line 23: SKOPEO: readonly variable
...
fedora-rawhide | 1..340
```

This is caused by a [regression](https://github.com/bats-core/bats-core/pull/904) in Bats 1.11.0.  So far it's harmless other than the visual noise.

**Comment by debarshiray** [comment]
> It's trying to use `skopeo(1)` to upload a `fedora-toolbox:34` image that was already downloaded into a local directory onto a temporary local Docker registry created by the test suite. So, I don't think the `fedora-toolbox:34` image disappeared from `registry.fedoraproject.org`, because the image got downloaded. For some reason the `skopeo copy ...` can't upload it.
> 
> I think I will need a Fedora 40 system to debug this. Fedora 40 Beta will be released later today, so it's good timing. :)
> 
> For context:
> 
> We download a bunch of images using `skopeo copy ...` while setting up the test suite, and cache them in a separate directory using the `dir:` notation, where they don't show up in `podman images`, etc.. Then we use `skopeo copy ...` to either place them in `containers-storage:` to make them visible to Podman, or to upload them to the temporary local Docker registry created by the test suite, as necessary. This way each test can start with a clean slate, but we don't have to repeatedly download the images again and again.

I filed a Skopeo issue for this:
https://github.com/containers/skopeo/issues/2309

**Comment by debarshiray** [comment]
recheck

**Comment by TristanCacqueray** [comment]
Not sure if the failure is caused by a missing requirement or a test tool, but that error looks legitimate: `Error: could not find slirp4netns, the network namespace can't be configured: exec: "slirp4netns": executable file not found in $PATH`

**Comment by debarshiray** [comment]
> Not sure if the failure is caused by a missing requirement or a test tool, but that error looks legitimate: `Error: could not find slirp4netns, the network namespace can't be configured: exec: "slirp4netns": executable file not found in $PATH`

Yeah, it's caused by `slirp4nets` being [changed](https://src.fedoraproject.org/rpms/containers-common/c/13c232f06411386002c2f9a0eff4ad1efb16f476) to a `Suggests` in `containers-common-extra`.

**Comment by debarshiray** [comment]
recheck

**Comment by TristanCacqueray** [comment]
recheck ci outage because of no space left on logserver

**Comment by debarshiray** [comment]
> recheck ci outage because of no space left on logserver

I see.  Thanks for fixing that!

**Comment by debarshiray** [comment]
> > It's trying to use `skopeo(1)` to upload a `fedora-toolbox:34` image that was already downloaded into a local directory onto a temporary local Docker registry created by the test suite. So, I don't think the `fedora-toolbox:34` image disappeared from `registry.fedoraproject.org`, because the image got downloaded. For some reason the `skopeo copy ...` can't upload it.
> > I think I will need a Fedora 40 system to debug this. Fedora 40 Beta will be released later today, so it's good timing. :)
> > For context:
> > We download a bunch of images using `skopeo copy ...` while setting up the test suite, and cache them in a separate directory using the `dir:` notation, where they don't show up in `podman images`, etc.. Then we use `skopeo copy ...` to either place them in `containers-storage:` to make them visible to Podman, or to upload them to the temporary local Docker registry created by the test suite, as necessary. This way each test can start with a clean slate, but we don't have to repeatedly download the images again and again.
> 
> I filed a Skopeo issue for this: [containers/podman#22575](https://github.com/containers/podman/issues/22575)

This was [worked around](https://github.com/containers/toolbox/commit/b58f9a51088afbfc22edb0b25776cfa2c4d8cc40) by forcing the use of `slirp4nets(1)`.

**Pull request merged**
