### PR TITLE
images: add Ubuntu 20.04 image

### PR DESCRIPTION
**Pull request by francesconicoletta**
This should add an Ubuntu 20.04 LTS image, the packages are pretty much the same as Fedora, plus libcap2-bin, needed to fix "/bin/bash not found in container".

### CODE REVIEW

**Comment by creatorofthesky** [comment]
I have noticed with all of these images that none of theme seem to work with apt / apt-get. The package manager is completely missing on every single image I have tried.

**Comment by Jmennius** [comment]
> I have noticed with all of these images that none of theme seem to work with apt / apt-get. The package manager is completely missing on every single image I have tried.

Did you try images from #483?

**Comment by andrewshadura** [comment]
See also #298, #371, #742.

**Comment by debarshiray** [comment]
https://github.com/containers/toolbox/pull/483 supersedes this.

**Comment by debarshiray** [comment]
Closing.

**Pull request closed without merging**
