### PR TITLE
Mount Smart Card Daemon socket (pcsd) inside the toolbox container

### PR DESCRIPTION
**Pull request by anthr76**
This takes insperation from:

* https://github.com/flatpak/flatpak/blob/684e68be094d072da7740223b7cbc5d06e9550f4/common/flatpak-run.c#L359-L383
* https://github.com/containers/toolbox/pull/625

This should allow tools like `ykman` to work with yubikeys.

### CODE REVIEW

**Comment by HarryMichal** [comment]
Hi @anthr76! Thanks for the PR! The change looks good. Could you only, please, squash the commits into one, change the `fix:` prefix to `src:` and add a link to this PR to the commit message? Thank you!

**Comment by anthr76** [comment]
Thanks @HarryMichal ! I had some fun with the squash process. Sorry about the commits. All should be good now 👍🏼

**Comment by HarryMichal** [comment]
> All should be good now 👍🏼

Just one tiny nitpick left. The link to the PR leads to list of commits, could you make the link lead to the base (conversation) part of it (https://github.com/containers/toolbox/pull/907)?

**Comment by anthr76** [comment]
Done

**Comment by HarryMichal** [comment]
Thank you for your work!

**Pull request merged**
