### PR TITLE
Add Code of Conduct

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>

As the title says.

### CODE REVIEW

**Comment by HarryMichal** [comment]
The tests are throwing a false positive. Can be merged.

**Comment by TomSweeneyRedHat** [comment]
@rhatdan PTAL

**Comment by rhatdan** [comment]
@debarshiray PTAL

**Comment by debarshiray** [comment]
Thanks, @TomSweeneyRedHat !

**Pull request merged**
