### PR TITLE
Images: Add Ubuntu 24.04 (new LTS) and remove Ubuntu 23.04 (EOL interim)

### PR DESCRIPTION
**Pull request by Jmennius**
Quite simple, it does seem to work :)

Fixes: #1481

### CODE REVIEW

**Review by Foxboron — APPROVED** [review]

**Review by travier — APPROVED** [review]

**Comment by travier** [comment]
Thanks!

**Comment by travier** [comment]
Ah, my bad, I missed that this was the general toolbox repo and I think here we keep all versions of the images (i.e. we don't remove EOL'ed ones) in the repo.

**Comment by travier** [comment]
Could you make a follow-up PR to re-add the EOL'ed 23.04 ones but not build them? Thanks

**Comment by Jmennius** [comment]
> Ah, my bad, I missed that this was the general toolbox repo and I think here we keep all versions of the images (i.e. we don't remove EOL'ed ones) in the repo.

oh really? I think there was one that we have removed as well before... (22.10 in #1416)

**Comment by travier** [comment]
Ah, good point. I'll let @debarshiray decide. I don't mind either way, it's all in the history.

**Comment by debarshiray** [comment]
Thanks for taking care of this, @Jmennius @travier @Foxboron !

> Ah, my bad, I missed that this was the general toolbox repo and I think here we keep all versions of the images (i.e. we don't remove EOL'ed ones) in the repo.

I don't have a strong opinion.  I keep the sources of the EOL:ed `fedora-toolbox` images around because I sometimes find them useful to track down some historical factoid.  If some image maintainer wants to remove them, then so be it.  :)

**Pull request merged**
