### PR TITLE
Add Arch Linux toolbox image

### PR DESCRIPTION
**Pull request by erazemk**
*This PR builds on the previous tries (#328 and #520) of including an Arch Linux image in toolbox.*

The PR adds an Arch Linux image, created from the upstream base-devel branch.

It includes most of the packages that the Fedora-based images do, but currently excludes flatpak (required for flatpak-spawn), since it adds ~690 MB of extra packages/dependencies.

The base-devel image (without any extra packages) is 729 MB, when syncing repositories 741 MB and with all the packages (excluding flatpak) 831 MB, which should be the minimum if based on archlinux:base-devel.

If the final size is very important I can try and base it off of `archlinux:latest` (which includes only the base packages, not base-devel), but that would still require adding some of the missing packages - although the base image size is 416 MB, which is quite an improvement..

Another option could be to separate latest and base-devel versions into separate images, similarly to what is done with Fedora versions.

I can also add the [yay AUR helper](https://github.com/Jguer/yay) if there is a need for it.

### CODE REVIEW

**Comment by xPMo** [comment]
Didn't work for me, but I figured it out.
I saw that a mount was failing by manually starting the container: `podman container start  --interactive --attach archlinux-toolbox`

Adding this line to the Dockerfile fixed that.

```
RUN touch /etc/machine-id
```

I also added a sudoers entry for the `%wheel` for mine container.

**Comment by erazemk** [comment]
I just now realized that the proper way to create and test custom images is by building them and using `toolbox create --image` to use them with toolbox.

I tried running the container that way, but got the error `Error: invalid entry point PID of container`, but that was fixed by adding `/etc/machine-id` to the image, like you recommended, but I got the following error:

```sh
bash: PROMPT_COMMAND: line 0: syntax error near unexpected token `;'
bash: PROMPT_COMMAND: line 0: ` ; printf "\033]0;%s@%s:%s\007" "${USER}" "${HOSTNAME%%.*}" "${PWD/#$HOME/\~}"'
```

Do you not get this error and if so, which OS are you using?

**Comment by xPMo** [comment]
I'm not getting that error, I'm not sure where that is coming from (it doesn't match any code in `toolbox` afaik). Maybe that's coming from your ~/.bashrc? That may still be something that can be fixed in the container config, but more likely is just some assumption that your bashrc is making.

> which OS are you using?

[Latest toolbox on an Arch host.](https://archlinux.org/packages/community/x86_64/toolbox/)

**Comment by erazemk** [comment]
> Maybe that's coming from your ~/.bashrc?

It seems the problem was indeed with this, I use the fish shell, so I don't have a local bashrc file, just the system one (which I haven't changed). This is weird though, since I based the Dockerfile off of the Fedora files, which work normally with toolbox. Copying the root user's bashrc doesn't help either, I still get the same error.

> That may still be something that can be fixed in the container config, but more likely is just some bad assumption that your bashrc is making. What do you get from `grep -A5 PROMPT_COMMAND ~/.bash*`?

When replacing `~/.bash*` with `/etc/bashrc` I get the following output:
```bash
   if [ -z "$PROMPT_COMMAND" ]; then
      case $TERM in
      xterm*|vte*)
        if [ -e /etc/sysconfig/bash-prompt-xterm ]; then
            PROMPT_COMMAND=/etc/sysconfig/bash-prompt-xterm
        elif [ "${VTE_VERSION:-0}" -ge 3405 ]; then
            PROMPT_COMMAND="__vte_prompt_command"
        else
            PROMPT_COMMAND='printf "\033]0;%s@%s:%s\007" "${USER}" "${HOSTNAME%%.*}" "${PWD/#$HOME/\~}"'
        fi
        ;;
      screen*)
        if [ -e /etc/sysconfig/bash-prompt-screen ]; then
            PROMPT_COMMAND=/etc/sysconfig/bash-prompt-screen
        else
            PROMPT_COMMAND='printf "\033k%s@%s:%s\033\\" "${USER}" "${HOSTNAME%%.*}" "${PWD/#$HOME/\~}"'
        fi
        ;;
      *)
        [ -e /etc/sysconfig/bash-prompt-default ] && PROMPT_COMMAND=/etc/sysconfig/bash-prompt-default
        ;;
      esac
    fi
    # Turn on parallel history
    shopt -s histappend
```

**Comment by xPMo** [comment]
> I use the fish shell, so I don't have a local bashrc file

Yeah, I use Zsh.

I tried replacing my ~/.bashrc /etc/bashrc from my Fedora toolbox and couldn't reproduce the issue.
Let's try tracing:

```bash
PS4='${FUNCNAME[*]}:$BASH_LINENO> ' bash -xi 2> >(grep -C4 PROMPT_COMMAND)
```

**Comment by xPMo** [comment]
https://bugs.archlinux.org/task/71002

**Comment by xPMo** [comment]
@erazemk: I closed #716 about the profile errors, Arch's image should add the `vte-common` package to support VTE terminals on hosts. I updated [my `arch-img` branch to include it](https://github.com/erazemk/toolbox/compare/master...xPMo:arch-img?expand=2).

**Pull request closed without merging**
