### PR TITLE
Added directory for f38 image

### PR DESCRIPTION
**Pull request by nievesmontero**
https://github.com/containers/toolbox/issues/1111

Signed-off-by: Nieves Montero <nmontero@redhat.com>

### CODE REVIEW

**Comment by matthiasclasen** [comment]
This looks good to me

**Comment by HarryMichal** [comment]
Thanks @nievesmontero, this looks good!

Just a small nitpick: In commit messages try to use imperative form for the "header" of a commit message. In this case your commit message would translate from `Added directory for f38 image` to `Add directory for f38 image`. My personal favorite for "how to write commit messages" is https://cbea.ms/git-commit.

**Comment by juhp** [comment]
Btw I think #1124 is missing here.

**Comment by matthiasclasen** [comment]
@nievesmontero can you check that and send a pr to fix it?

**Comment by nievesmontero** [comment]
Sure, I’ll check it and try to correct it.Regards,Nieves Montero FernándezEl 28 sept 2022, a las 19:42, Matthias Clasen ***@***.***> escribió:﻿
@nievesmontero can you check that and send a pr to fix it?

**Comment by nievesmontero** [comment]
@matthiasclasen sure, I’ll check it and try to correct it.

**Comment by nievesmontero** [comment]
The problem has been fixed on the following pull request 
https://github.com/containers/toolbox/pull/1131

**Pull request merged**
