### PR TITLE
Add Arch Linux toolbox image

### PR DESCRIPTION
**Pull request by erazemk**
This PR is a continuation of #328.

Tested with `podman build --tag archlinux:latest ./Dockerfile`, but with a few problems:

* Image is 1.87 GB, possibly because of base-devel or kernel (Arch's image from Dockerhub is 426 MB)
* Can't enter the container with `podman run --name arch-test --rm localhost/archlinux` (even though it is listed when running `podman images`)

The following packages were installed when building the image:
```
dnssec-anchors-20190629-2  elfutils-0.180-1  gc-8.0.4-4  guile-2.2.6-2  icu-67.1-1  iproute2-5.7.0-1
iputils-20190709-2  ldns-1.7.1-2  libcroco-0.6.13-2  libedit-20191231_3.1-1  libmicrohttpd-0.9.71-1
libmpc-1.1.0-2  libpipeline-1.5.2-1  libxml2-2.9.10-2  mkinitcpio-28-1  mkinitcpio-busybox-1.31.1-1
pciutils-3.7.0-1  perl-error-0.17029-2  perl-mailtools-2.21-4  perl-timedate-2.33-2  psmisc-23.3-2
systemd-sysvcompat-245.7-1  xxhash-0.8.0-1  autoconf-2.69-7  automake-1.16.2-3  base-2-2
bash-completion-2.10-2  binutils-2.34-5  bison-3.6.4-1  curl-7.71.1-1  diffutils-3.7-3  fakeroot-1.24-2
file-5.39-1  findutils-4.7.0-2  flex-2.6.4-3  gawk-5.1.0-1  gcc-10.1.0-2  gettext-0.20.2-1
git-2.28.0-1  grep-3.4-1  groff-1.22.4-3  gzip-1.10-3  keyutils-1.6.3-1  less-551-3
libtool-2.4.6+42+gb88cebd5-13  linux-5.7.11.arch1-1  linux-firmware-20200721.2b823fc-1  lsof-4.93.2-3
m4-1.4.18-3  make-4.3-3  man-db-2.9.3-1  man-pages-5.07-1  mlocate-0.26.git.20170220-3  mtr-0.93-3
openssh-8.3p1-3  pacman-5.2.2-1  patch-2.7.6-8  pkgconf-1.7.3-1  rsync-3.2.2-2  sed-4.8-1  sudo-1.9.2-1
tcpdump-4.9.3-2  texinfo-6.7-3  time-1.9-3  traceroute-2.1.0-5  tree-1.8.0-2  unzip-6.0-14
wget-1.20.3-3  which-2.21-5  whois-5.5.6-1  zip-3.0-9
```

I also don't know what to do about man-pages, are they required, should they be removed?

### CODE REVIEW

**Comment by erazemkokot** [comment]
Regarding `Error: invalid entry point PID of container running`, I got the same error when trying to run `toolbox create --image docker.io/library/archlinux:latest` and I don't know what it means.

**Comment by Limero** [comment]
Thank you for making this. I hope it can get fixed up and merged soon!

A few pointers:
* `RUN pacman -Syu --noconfirm` and `RUN pacman -Sy --noconfirm $(<extra-packages)` can be done at once with `RUN pacman -Syu --noconfirm $(<extra-packages)`
* sudo is already part of base-devel
* You should be able to skip linux-firmware, no need to have 500MB of proprietary wifi drivers and such in the container
* How about the AUR helper `yay` installed by default too?

**Comment by erazemkokot** [comment]
> * `RUN pacman -Syu --noconfirm` and `RUN pacman -Sy --noconfirm $(<extra-packages)` can be done at once with `RUN pacman -Syu --noconfirm $(<extra-packages)`

Thanks, I'll update it.

> * sudo is already part of base-devel
> * You should be able to skip linux-firmware, no need to have 500MB of proprietary wifi drivers and such in the container

I was thinking that might be the case. Is `linux` unneeded as well (doesn't toolbox use the host's kernel)?

> * How about the AUR helper `yay` installed by default too?

Great idea, but I'm totally new to Docker and containers in general, so if you know how to implement this or have any other ideas, I'd welcome patches or a pull request :)

**Comment by Limero** [comment]
> > * `RUN pacman -Syu --noconfirm` and `RUN pacman -Sy --noconfirm $(<extra-packages)` can be done at once with `RUN pacman -Syu --noconfirm $(<extra-packages)`
> 
> Thanks, I'll update it.
> 
> > * sudo is already part of base-devel
> > * You should be able to skip linux-firmware, no need to have 500MB of proprietary wifi drivers and such in the container
> 
> I was thinking that might be the case. Is `linux` unneeded as well (doesn't toolbox use the host's kernel)?
> 
> > * How about the AUR helper `yay` installed by default too?
> 
> Great idea, but I'm totally new to Docker and containers in general, so if you know how to implement this or have any other ideas, I'd welcome patches or a pull request :)

Oh, yeah. You should be able to skip the `linux` package too. We can wait with adding an AUR helper until this is merged.

**Comment by erazemkokot** [comment]
@Limero Done. Can you please take care of installing yay?

**Comment by Limero** [comment]
> @Limero Done. Can you please take care of installing yay?

Let's add that later once this base is merged.

**Comment by erazemkokot** [comment]
Oh, my bad. I though you meant we'll add it after I merge the pacman changes.

Do you maybe know why the build fails/how to fix it?

**Comment by Limero** [comment]
> Oh, my bad. I though you meant we'll add it after I merge the pacman changes.
> 
> Do you maybe know why the build fails/how to fix it?

Sorry, I don't know. The toolbox maintainers might be able to help solve it.

**Comment by erazemkokot** [comment]
@HarryMichal Sorry for tagging you randomly like this, but you're the person who responded when I submitted the last version of the pull request. I've successfully built the image (although it's 1.23 GB for some reason), but when trying to run it with `podman run --name toolbox --rm localhost/toolbox -v`, I get the message `Error: executable file not found in $PATH: No such file or directory: OCI runtime command not found error` and the command exits. I'm not sure what to do at this point.

**Pull request closed without merging**
