### PR TITLE
pkg/utils, test/system: Retain errors without -v when forwarding to host

### PR DESCRIPTION
**Pull request by debarshiray**
https://github.com/containers/toolbox/issues/957
https://github.com/containers/toolbox/pull/1052

### CODE REVIEW

**Comment by debarshiray** [comment]
recheck

**Comment by debarshiray** [comment]
@danpawlik @TristanCacqueray Any idea why the Fedora Rawhide nodes are reporting `NODE_FAILURE` ?

**Comment by TristanCacqueray** [comment]
The image appears broken again, from the nodepool logs we see `Exception: Timeout connecting to xxx on port 22`

**Comment by TristanCacqueray** [comment]
recheck

**Comment by debarshiray** [comment]
> The image appears broken again, from the nodepool logs we see `Exception: Timeout connecting to xxx on port 22`. It's probably related to a recent outage from our cloud provider. It should be fixed now.

Thanks for checking, @TristanCacqueray !

**Pull request merged**
